### ISSUE TITLE
Fix HTTPS & Project Config

### ISSUE THREAD

**Issue by KRXTCH** [Antonin-Artaud/Aled#21]
Des problèmes de connexions entre le front et le back sont apparus suite à l'ajout de la configuration https du projet web api.

De plus, l'installation et la gestion du projet sont assez difficiles à cause de nos environnements de développement différents.

**Comment by Antonin-Artaud** [comment]
Je teste ta PR sur mon Mac pour voir si la config marche chez moi aussi et je valide si ça marche

**Comment by KRXTCH** [comment]
@Antonin-Artaud je t'ai envoyé le tuto sur discord
