### ISSUE TITLE
Email confirmation process

### ISSUE THREAD

**Issue by KRXTCH** [Antonin-Artaud/Aled#33]
Faire le process d'envoie d'e-mail : 
- envoie d'un mail au moment de l'inscription
- envoie d'un mail si click sur la verid d'email dans les paramètres de l'app

coté back :
- générér un token et envoyer un email au moment du register
- créer une route sur le controller account qui génère un token et envoie le mail de confirmation de mail

**Comment by Antonin-Artaud** [comment]
pour le back : 
 -> générér un token et envoyer un email au moment du register : t'as déjà un endpoint pour générer le token. + un email service dans ABP déjà setup :) par contre on a pas de smtp pas sûr qu'on puisse tester sinon tu en installes un

**Comment by KRXTCH** [comment]
tqt c'est deja fait mdrrrr
