### ISSUE TITLE
Add identityClients conf for swagger scope

### ISSUE THREAD

**Issue by KRXTCH** [Antonin-Artaud/Aled#36]
Ajouté la conf identityClients au appsettings du HttpApi.Host en spécifiant le scope swagger (Aled_Swagger je crois) et non celui de l'app (Aled)

"IdentityClients": {
  "Default": {
        "GrantType": "password",
        "ClientId": "Aled_App", <-- voir si c'est le meme clientId
        "UserName": "admin",
        "UserPassword": "1q2w3E*",
        "Authority": "",
        "Scope": "Aled" <-- à changer
      }
  },

**Comment by Antonin-Artaud** [comment]
TICKET CLOS #43
